#ifndef __ADC_CONFIG_H__
#define __ADC_CONFIG_H__
#include "net_config.h"

#if (USERDEF_ADC_TASK == ENABLED)
#define BOARD_ADC16_0_BASE ADC0
#define BOARD_ADC16_0_CHANNEL_GROUP 0U
#define BOARD_ADC16_1_BASE ADC1
#define BOARD_ADC16_1_CHANNEL_GROUP 0U

#define BOARD_ADC16_0_USER_CHANNEL1 22U
#define BOARD_ADC16_0_USER_CHANNEL2 21U
#define BOARD_ADC16_0_USER_CHANNEL3 23U
#define BOARD_ADC16_1_USER_CHANNEL1 18U
#define BOARD_ADC16_1_USER_CHANNEL2 23U
#endif

#endif // __ADC_CONFIG_H__